---
  dataset:
    dataset_name: "add_sub"
    dataset_split: "validation"
    dataset_subset_name: null
    dataset_key_map:
      question: "sQuestion"
      answer: "lSolutions"
      id: "id"
  method:
    method_name: "batch_inference_chat"
    method_config_file_path: null
    method_args:
      client_name: "openai"
      transform: "batch_inference_chat.add_sub.transform_batch_inference_add_sub.BatchInferenceAddSubTransform"
      extract: "batch_inference_chat.add_sub.extract_batch_inference_add_sub_new.BatchInferenceAddSubExtract_new"
      extraction_regex: "[0-9.]+"
      prompt_file_path: "batch_inference_chat/add_sub/prompt-batch=6.txt"
      max_tokens: 512
      temperature: 0
      engine: gpt-3.5-turbo
      stop_sequence: "\n\n"
  metrics:
    - "exact_match"
