---
  dataset:
    dataset_name: "commonsense_qa"
    dataset_split: "validation"
    dataset_subset_name: null
    dataset_key_map:
      question: "question"
      choices: "choices"
      answer: "answerKey"
      id: "id"
  method:
    method_name: "cot_chat"
    method_config_file_path: null
    method_args:
      client_name: "openai"
      transform: "cot_chat.commonsense_qa.transform_cot_commonsense_qa.CoTCommonsenseQATransform"
      extract: "cot_chat.commonsense_qa.extract_cot_commonsense_qa.CoTCommonsenseQAExtract"
      extraction_regex: '.* (.*)\).\n?'
      prompt_file_path: "cot_chat/commonsense_qa/prompt.txt"
      max_tokens: 512
      temperature: 0
      engine: gpt-3.5-turbo
      stop_sequence: "\n\n"
  metrics:
    - "exact_match"
